# Generated by Django 3.0.5 on 2020-10-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_remove_todo_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.ImageField(blank=True, upload_to='media_root/pictures'),
        ),
    ]
